apiVersion: v1
kind: ServiceAccount
metadata:
  name: registerwerk-backup
  labels:
    app.kubernetes.io/name: registerwerk-backup
    app.kubernetes.io/component: database-backup
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.s3Credentials.useIrsa }}
