package de.makibytes.registerwerk.erc3643.internal;

import de.makibytes.registerwerk.deployment.api.AssetLookupPort;
import de.makibytes.registerwerk.erc3643.events.Erc3643SuiteDeployedEvent;
import org.springframework.context.ApplicationEventPublisher;
import de.makibytes.registerwerk.shared.EntityNotFoundException;
import de.makibytes.registerwerk.blockchain.api.BlockchainClientRegistry;
import de.makibytes.registerwerk.blockchain.api.ClaimSigningService;
import de.makibytes.registerwerk.blockchain.api.ContractAddressConfig;
import de.makibytes.registerwerk.blockchain.api.EvmContractService;
import de.makibytes.registerwerk.blockchain.api.EvmUtils;
import de.makibytes.registerwerk.blockchain.api.TokenDeploymentResult;
import de.makibytes.registerwerk.chain.api.ChainDescriptor;
import de.makibytes.registerwerk.chain.api.ExplorerUrlBuilder;
import de.makibytes.registerwerk.deployment.api.AssetDeployment;
import de.makibytes.registerwerk.chain.api.ChainConfig;
import de.makibytes.registerwerk.erc3643.api.Erc3643ClaimTopic;
import de.makibytes.registerwerk.erc3643.api.Erc3643ClaimTopicRepository;
import de.makibytes.registerwerk.erc3643.api.Erc3643Suite;
import de.makibytes.registerwerk.erc3643.api.OnchainClaim;
import de.makibytes.registerwerk.erc3643.api.OnchainIdentity;
import de.makibytes.registerwerk.deployment.api.AssetDeploymentRepository;
import de.makibytes.registerwerk.chain.api.ChainConfigRepository;
import de.makibytes.registerwerk.erc3643.api.Erc3643SuiteRepository;
import de.makibytes.registerwerk.erc3643.api.OnchainClaimRepository;
import de.makibytes.registerwerk.erc3643.api.OnchainIdentityRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.web3j.abi.datatypes.Address;
import org.web3j.abi.datatypes.DynamicArray;
import org.web3j.abi.datatypes.DynamicBytes;
import org.web3j.abi.datatypes.DynamicStruct;
import org.web3j.abi.datatypes.Function;
import org.web3j.abi.datatypes.Type;
import org.web3j.abi.datatypes.Utf8String;
import org.web3j.abi.datatypes.generated.Bytes32;
import org.web3j.abi.datatypes.generated.Uint256;
import org.web3j.abi.datatypes.generated.Uint16;
import org.web3j.abi.datatypes.generated.Uint8;
import org.web3j.abi.TypeReference;
import org.web3j.crypto.Credentials;
import org.web3j.protocol.Web3j;
import org.web3j.protocol.core.methods.response.TransactionReceipt;
import org.web3j.utils.Numeric;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;

/**
 * Service responsible for deploying ERC-3643 (T-REX) security token suites on-chain.
 *
 * <p>Each T-REX suite consists of six contracts:
 * <ol>
 *   <li>Token – ERC-20-compatible security token with compliance hooks</li>
 *   <li>IdentityRegistry – maps wallet addresses to ONCHAINID identities</li>
 *   <li>IdentityRegistryStorage – persistent storage for the identity registry</li>
 *   <li>ClaimTopicsRegistry – enumerates required claim topics for all holders</li>
 *   <li>TrustedIssuersRegistry – whitelists claim issuers per topic</li>
 *   <li>ModularCompliance – pluggable rule engine for transfer restrictions</li>
 * </ol>
 *
 * <p>Full Web3j deployment requires contract wrappers generated by the
 * {@code web3j-maven-plugin} from the Foundry-compiled T-REX ABIs.
 * Until those wrappers are available the deployment methods return placeholder suites.
 */
@Service
@Transactional
public class Erc3643DeploymentService {

    private static final Logger log = LoggerFactory.getLogger(Erc3643DeploymentService.class);

    /** Standard T-REX claim topic: Know Your Customer. */
    public static final long CLAIM_TOPIC_KYC = 1L;

    /** Standard T-REX claim topic: Anti-Money Laundering. */
    public static final long CLAIM_TOPIC_AML = 2L;

    /**
     * keccak256("EwpgSuiteDeployed(bytes32,address,address,address)") — topic0 of
     * {@code EwpgTREXFactory.EwpgSuiteDeployed} event used to extract contract addresses.
     */
    private static final String REGISTERWERK_SUITE_DEPLOYED_TOPIC =
            "0x" + org.web3j.crypto.Hash.sha3String(
                    "EwpgSuiteDeployed(bytes32,address,address,address)");

    private final BlockchainClientRegistry clientRegistry;
    private final OnchainIdentityRepository identityRepository;
    private final OnchainClaimRepository claimRepository;
    private final Erc3643SuiteRepository suiteRepository;
    private final Erc3643ClaimTopicRepository claimTopicRepository;
    private final AssetDeploymentRepository deploymentRepository;
    private final AssetLookupPort assetLookupPort;
    private final ApplicationEventPublisher eventPublisher;
    private final ExplorerUrlBuilder explorerUrlBuilder;
    private final ChainConfigRepository chainConfigRepository;
    private final EvmContractService evmContractService;
    private final ContractAddressConfig contractAddressConfig;
    private final ClaimSigningService claimSigningService;

    public Erc3643DeploymentService(
            BlockchainClientRegistry clientRegistry,
            OnchainIdentityRepository identityRepository,
            OnchainClaimRepository claimRepository,
            Erc3643SuiteRepository suiteRepository,
            Erc3643ClaimTopicRepository claimTopicRepository,
            AssetDeploymentRepository deploymentRepository,
            AssetLookupPort assetLookupPort,
            ApplicationEventPublisher eventPublisher,
            ExplorerUrlBuilder explorerUrlBuilder,
            ChainConfigRepository chainConfigRepository,
            EvmContractService evmContractService,
            ContractAddressConfig contractAddressConfig,
            ClaimSigningService claimSigningService) {
        this.clientRegistry = clientRegistry;
        this.identityRepository = identityRepository;
        this.claimRepository = claimRepository;
        this.suiteRepository = suiteRepository;
        this.claimTopicRepository = claimTopicRepository;
        this.deploymentRepository = deploymentRepository;
        this.assetLookupPort = assetLookupPort;
        this.eventPublisher = eventPublisher;
        this.explorerUrlBuilder = explorerUrlBuilder;
        this.chainConfigRepository = chainConfigRepository;
        this.evmContractService = evmContractService;
        this.contractAddressConfig = contractAddressConfig;
        this.claimSigningService = claimSigningService;
    }

    /**
     * Deploy a full T-REX suite for the given asset deployment.
     *
     * <p>Steps (when contract wrappers are available):
     * <ol>
     *   <li>Resolve the {@code ChainConfig} for this deployment</li>
     *   <li>Build {@code TokenDetails} and {@code ClaimDetails} from the asset config</li>
     *   <li>Encode and submit the {@code deployTREXSuite} transaction via Web3j</li>
     *   <li>Wait for receipt and extract deployed contract addresses from events</li>
     *   <li>Save {@link Erc3643Suite} record</li>
     *   <li>Confirm the {@link AssetDeployment} as CONFIRMED</li>
     * </ol>
     *
     * @param assetId       ID of the asset to deploy
     * @param chainConfigId ID of the chain configuration to deploy on
     * @param actorId       ID of the user initiating the deployment (for audit)
     * @return future resolving to the saved {@link Erc3643Suite}
     */
    public CompletableFuture<Erc3643Suite> deploy(UUID assetId, UUID chainConfigId, UUID actorId) {
        log.info("Deploying ERC-3643 suite for asset={} on chainConfig={}", assetId, chainConfigId);

        // Validate asset deployment exists
        deploymentRepository.findByAssetId(assetId).stream()
            .findFirst()
            .orElseThrow(() -> new EntityNotFoundException("AssetDeployment for asset", assetId));

        AssetDeployment deployment = deploymentRepository.findByAssetId(assetId).stream()
                .findFirst()
                .orElseThrow(() -> new EntityNotFoundException("AssetDeployment for asset", assetId));

        return CompletableFuture.supplyAsync(() -> {
            ChainConfig chainConfig = chainConfigRepository.findById(chainConfigId)
                    .orElseThrow(() -> new EntityNotFoundException("ChainConfig", chainConfigId));

            String factoryAddress = contractAddressConfig.requireTrexFactory(chainConfig.getIdentifier());
            Web3j web3j = clientRegistry.getEvmClientByIdentifier(chainConfig.getIdentifier());
            Credentials creds = evmContractService.credentials(chainConfigId);

            // CREATE2 salt: deterministic per asset
            String salt = "registerwerk-" + assetId.toString();

            // Encode assetId as bytes32
            byte[] assetIdBytes = EvmUtils.uuidToBytes32(assetId);

            AssetLookupPort.AssetInfo assetInfo = assetLookupPort.findById(assetId)
                    .orElseThrow(() -> new EntityNotFoundException("Asset", assetId));
            String assetName = assetInfo.name();
            String assetSymbol = deriveSymbol(assetName);

            Function fn = buildDeployEwpgSuiteFunction(assetIdBytes, salt, creds.getAddress(), assetName, assetSymbol);
            evmContractService.send(web3j, creds, factoryAddress, fn);

            Erc3643Suite suite = resolveDeployedSuite(web3j, factoryAddress, salt, deployment.getId());
            Erc3643Suite saved = suiteRepository.save(suite);
            seedDefaultClaimTopics(saved.getId());

            eventPublisher.publishEvent(new Erc3643SuiteDeployedEvent(saved.getId(), actorId, "REGISTRY_ADMIN", java.util.Map.of()));

            return saved;
        });
    }

    /**
     * Deploy a full T-REX suite for the given asset deployment.
     * Overload accepting a {@link ChainDescriptor} for backwards compatibility with
     * {@link de.makibytes.registerwerk.application.asset.AssetDeploymentService}.
     *
     * @param assetId   ID of the asset to deploy
     * @param chain     legacy chain descriptor
     * @param ownerAddress  registry backend wallet address
     * @return future resolving to the deployment tx hash and the deployed suite's token address
     */
    public CompletableFuture<TokenDeploymentResult> deploy(
            UUID assetId, ChainDescriptor chain, String ownerAddress) {
        log.info("Deploying ERC-3643 suite for asset={} on chain={}", assetId, chain);
        // Delegate to the chainConfigId-based overload by finding a matching ChainConfig
        return CompletableFuture.supplyAsync(() -> {
            ChainConfig chainConfig = chainConfigRepository.findAll().stream()
                    .filter(c -> c.getIdentifier().equalsIgnoreCase(
                            chain.chain().name() + "_" + chain.network().name()))
                    .findFirst()
                    .orElse(null);

            if (chainConfig == null) {
                log.warn("No ChainConfig found for descriptor={}; returning placeholder", chain);
                return TokenDeploymentResult.txOnly("0x-PENDING-ERC3643-" + assetId);
            }

            AssetDeployment deployment = deploymentRepository.findByAssetId(assetId).stream()
                    .findFirst()
                    .orElseThrow(() -> new EntityNotFoundException("AssetDeployment for asset", assetId));

            String factoryAddress = contractAddressConfig.requireTrexFactory(chainConfig.getIdentifier());
            Web3j web3j = clientRegistry.getEvmClient(chain);
            Credentials creds = evmContractService.credentials(chain);
            String salt = "registerwerk-" + assetId;
            byte[] assetIdBytes = EvmUtils.uuidToBytes32(assetId);
            AssetLookupPort.AssetInfo assetInfo = assetLookupPort.findById(assetId)
                    .orElseThrow(() -> new EntityNotFoundException("Asset", assetId));
            Function fn = buildDeployEwpgSuiteFunction(assetIdBytes, salt, creds.getAddress(),
                    assetInfo.name(), deriveSymbol(assetInfo.name()));
            TransactionReceipt receipt = evmContractService.send(web3j, creds, factoryAddress, fn);

            // send() already waits for a mined, non-reverted receipt (throws otherwise), so the
            // suite genuinely exists on-chain now — resolve its real addresses via the factory's
            // own getSuiteAddresses(salt) view call rather than parsing event-log topics (the
            // previous approach only ever captured 3 of 6 addresses and, for the sibling overload,
            // was never even attempted here — see the ERC-3643 review's findings #2/#6).
            Erc3643Suite suite = resolveDeployedSuite(web3j, factoryAddress, salt, deployment.getId());
            Erc3643Suite saved = suiteRepository.save(suite);
            saved.setFactoryTxHash(receipt.getTransactionHash());
            suiteRepository.save(saved);
            seedDefaultClaimTopics(saved.getId());

            eventPublisher.publishEvent(new Erc3643SuiteDeployedEvent(
                    saved.getId(), null, "SYSTEM", java.util.Map.of()));

            return new TokenDeploymentResult(receipt.getTransactionHash(), saved.getTokenAddress());
        });
    }

    // Confidential ERC-3643 deployment is handled by ConfidentialErc3643Service (a real,
    // Web3j-backed implementation), routed via Erc3643DeploymentPortImpl.deployConfidential —
    // not here. An earlier, permanently-unreachable duplicate of this method used to sit in
    // this class throwing "not yet supported"; it was dead code (the port never called it) and
    // its message was stale even before removal.

    /**
     * Register an investor wallet with the T-REX IdentityRegistry.
     * This is required before the investor can hold or receive tokens.
     *
     * <p>Calls {@code IIdentityRegistry.registerIdentity(wallet, identityAddress, countryCode)}
     * via Web3j using the registry backend wallet (which must hold the agent role).
     *
     * @param holderId          ID of the legal entity (holder)
     * @param suiteId           ID of the ERC-3643 suite whose registry to update
     * @param walletAddress     investor's EVM wallet address
     * @param onchainIdentityId ID of the ONCHAINID record to link
     */
    public void registerInvestorIdentity(
            UUID holderId, UUID suiteId, String walletAddress, UUID onchainIdentityId) {
        log.info("Registering identity for holder={} in suite={}, wallet={}",
            holderId, suiteId, walletAddress);

        Erc3643Suite suite = suiteRepository.findById(suiteId)
            .orElseThrow(() -> new EntityNotFoundException("Erc3643Suite", suiteId));

        identityRepository.findById(onchainIdentityId)
            .orElseThrow(() -> new EntityNotFoundException("OnchainIdentity", onchainIdentityId));

        if (suite.getIdentityRegistryAddress() == null
                || suite.getIdentityRegistryAddress().startsWith("0x-PENDING")) {
            log.warn("registerInvestorIdentity: identity registry not yet deployed for suite={}",
                    suiteId);
            return;
        }

        OnchainIdentity identity = identityRepository.findById(onchainIdentityId)
                .orElseThrow(() -> new EntityNotFoundException("OnchainIdentity", onchainIdentityId));
        String identityAddress = identity.getIdentityAddress() != null
                ? identity.getIdentityAddress() : "0x0000000000000000000000000000000000000000";

        AssetDeployment dep = deploymentRepository.findById(suite.getAssetDeploymentId())
                .orElseThrow(() -> new EntityNotFoundException("AssetDeployment",
                        suite.getAssetDeploymentId()));
        ChainDescriptor descriptor = new ChainDescriptor(dep.getChain(), dep.getNetwork());
        Web3j web3j = clientRegistry.getEvmClient(descriptor);
        Credentials creds = evmContractService.credentials(descriptor);

        // IIdentityRegistry.registerIdentity(address _userAddress, address _identity, uint16 _country)
        Function fn = new Function(
                "registerIdentity",
                Arrays.asList(
                        new Address(walletAddress),
                        new Address(identityAddress),
                        new Uint16(java.math.BigInteger.ZERO) // default country 0
                ),
                Collections.emptyList()
        );
        evmContractService.send(web3j, creds, suite.getIdentityRegistryAddress(), fn);
        log.info("registerInvestorIdentity: registered wallet={} in suite={}", walletAddress, suiteId);
    }

    /**
     * Issue a KYC claim to an investor's ONCHAINID contract.
     *
     * <p>Signs a claim off-chain and calls
     * {@code ONCHAINID.addClaim(topic, scheme, issuer, signature, data, uri)}.
     * The registry backend wallet must be registered as a TrustedIssuer in the TIR.
     *
     * @param onchainIdentityId ID of the ONCHAINID record to receive the claim
     * @param claimTopic        claim topic number (e.g. {@link #CLAIM_TOPIC_KYC})
     * @param expiresAt         optional expiry baked into the signed claim data; {@code null} means none
     */
    public void issueKycClaim(UUID onchainIdentityId, long claimTopic, java.time.Instant expiresAt) {
        log.info("Issuing claim topic={} to identity={}", claimTopic, onchainIdentityId);

        OnchainIdentity identity = identityRepository.findById(onchainIdentityId)
                .orElseThrow(() -> new EntityNotFoundException("OnchainIdentity", onchainIdentityId));

        String identityAddress = identity.getIdentityAddress();
        if (identityAddress == null || identityAddress.startsWith("0x-PENDING")) {
            log.warn("issueKycClaim: identity not yet deployed for id={}; skipping on-chain call",
                    onchainIdentityId);
            return;
        }

        // Sign via ClaimSigningService — real ABI encoding (abi.encode(address,uint256,bytes) for
        // the claim hash, matching OnchainID's ClaimIssuer.isClaimValid exactly). Using the same
        // signer here that submits the tx below is required: the trusted-issuer address
        // registered on-chain must equal the recovered signer.
        ClaimSigningService.SignedClaim signed = claimSigningService.signClaim(
                identity.getChainConfigId(), identityAddress, claimTopic, expiresAt);

        Credentials creds = evmContractService.credentials(identity.getChainConfigId());

        // ONCHAINID.addClaim(uint256 topic, uint256 scheme, address issuer,
        //                    bytes signature, bytes data, string uri)
        ChainConfig chainConfig = chainConfigRepository.findById(identity.getChainConfigId())
                .orElseThrow(() -> new EntityNotFoundException("ChainConfig",
                        identity.getChainConfigId()));
        Web3j web3j = clientRegistry.getEvmClientByIdentifier(chainConfig.getIdentifier());

        Function fn = new Function(
                "addClaim",
                Arrays.asList(
                        new Uint256(java.math.BigInteger.valueOf(claimTopic)),
                        new Uint256(java.math.BigInteger.ONE),                // scheme = 1 (ECDSA)
                        new Address(signed.issuerAddress()),
                        new DynamicBytes(Numeric.hexStringToByteArray(signed.claimSignature())),
                        new DynamicBytes(Numeric.hexStringToByteArray(signed.claimData())),
                        new Utf8String("")
                ),
                Collections.emptyList()
        );
        evmContractService.send(web3j, creds, identityAddress, fn);
        log.info("issueKycClaim: topic={} issued on identity={}", claimTopic, identityAddress);
    }

    /**
     * Revoke a claim (e.g. when KYC expires or an investor fails re-verification).
     *
     * <p>Calls {@code ONCHAINID.removeClaim(claimId)} via Web3j.
     *
     * @param onchainClaimId ID of the {@code OnchainClaim} record to revoke
     */
    public void revokeKycClaim(UUID onchainClaimId) {
        log.info("Revoking claim={}", onchainClaimId);

        OnchainClaim claim = claimRepository.findById(onchainClaimId)
                .orElseThrow(() -> new EntityNotFoundException("OnchainClaim", onchainClaimId));
        OnchainIdentity identity = identityRepository.findById(claim.getOnchainIdentityId())
                .orElseThrow(() -> new EntityNotFoundException("OnchainIdentity",
                        claim.getOnchainIdentityId()));

        String identityAddress = identity.getIdentityAddress();
        if (identityAddress == null || identityAddress.startsWith("0x-PENDING")) {
            log.warn("revokeKycClaim: identity not yet deployed; skipping on-chain call");
            return;
        }

        // ERC-735 claimId = keccak256(abi.encode(issuer, topic))
        Credentials creds = evmContractService.credentials(identity.getChainConfigId());
        byte[] claimId = org.web3j.crypto.Hash.sha3(
                encodeClaimId(creds.getAddress(), claim.getTopic()));

        ChainConfig chainConfig = chainConfigRepository.findById(identity.getChainConfigId())
                .orElseThrow(() -> new EntityNotFoundException("ChainConfig",
                        identity.getChainConfigId()));
        Web3j web3j = clientRegistry.getEvmClientByIdentifier(chainConfig.getIdentifier());

        // ONCHAINID.removeClaim(bytes32 claimId)
        Function fn = new Function(
                "removeClaim",
                List.of(new Bytes32(claimId)),
                Collections.emptyList()
        );
        evmContractService.send(web3j, creds, identityAddress, fn);
        log.info("revokeKycClaim: claim={} removed from identity={}", onchainClaimId, identityAddress);
    }

    // ── Suite deployment helpers ──────────────────────────────────────────────

    private static final String ZERO_ADDRESS = "0x0000000000000000000000000000000000000000";

    /**
     * Builds the {@code deployEwpgSuite(bytes32, string, TokenDetails, ClaimDetails)} call.
     *
     * TokenDetails: (address owner, string name, string symbol, uint8 decimals,
     *   address irs, address ONCHAINID, address[] irAgents, address[] tokenAgents,
     *   address[] complianceModules, bytes[] complianceSettings)
     * ClaimDetails: (uint256[] claimTopics, address[] issuers, uint256[][] issuerClaims)
     *
     * <p>{@code issuers}/{@code issuerClaims} must be the same length — {@code TREXFactory
     * .deployTREXSuite} reverts with {@code InvalidClaimPattern()} otherwise. There is exactly
     * one issuer (the registry backend wallet), trusted for every topic in {@code claimTopics}
     * (KYC + AML).
     */
    @SuppressWarnings({"unchecked", "rawtypes"})
    private static Function buildDeployEwpgSuiteFunction(
            byte[] assetIdBytes, String salt, String ownerAddress, String name, String symbol) {

        DynamicStruct tokenDetails = new DynamicStruct(
                new Address(ownerAddress),
                new Utf8String(name),
                new Utf8String(symbol),
                new Uint8(java.math.BigInteger.valueOf(18)),
                new Address(ZERO_ADDRESS),                               // IRS: zero = deploy new
                new Address(ZERO_ADDRESS),                               // ONCHAINID: zero = deploy new
                new DynamicArray<>(Address.class, new Address(ownerAddress)), // irAgents
                new DynamicArray<>(Address.class, new Address(ownerAddress)), // tokenAgents
                new DynamicArray<>(Address.class),                       // complianceModules (empty)
                new DynamicArray<>(DynamicBytes.class)                   // complianceSettings (empty)
        );

        // Required topics: KYC + AML (AML revocation must also be visible to the on-chain
        // compliance gate). The registry wallet is the sole trusted issuer for both at deploy
        // time; more can be added later via addTrustedIssuer.
        List<Uint256> requiredTopics = List.of(
                new Uint256(java.math.BigInteger.valueOf(CLAIM_TOPIC_KYC)),
                new Uint256(java.math.BigInteger.valueOf(CLAIM_TOPIC_AML)));

        DynamicStruct claimDetails = new DynamicStruct(
                new DynamicArray<>(Uint256.class, requiredTopics),
                new DynamicArray<>(Address.class, new Address(ownerAddress)),
                new DynamicArray<>(DynamicArray.class,
                        new DynamicArray<>(Uint256.class, requiredTopics))   // issuerClaims[0] = same topics
        );

        return new Function(
                "deployEwpgSuite",
                Arrays.asList(
                        new Bytes32(assetIdBytes),
                        new Utf8String(salt),
                        tokenDetails,
                        claimDetails
                ),
                Collections.emptyList()
        );
    }

    private static String deriveSymbol(String assetName) {
        return de.makibytes.registerwerk.blockchain.api.EvmUtils.tokenSymbol(assetName);
    }

    /**
     * Resolves all six deployed T-REX suite contract addresses via {@code EwpgTREXFactory
     * .getSuiteAddresses(salt)} — a single {@code eth_call} — rather than parsing the
     * {@code EwpgSuiteDeployed} event log, which previously only carried three of the six
     * addresses (token, identityRegistry, compliance) and left {@code identityRegistryStorage}/
     * {@code claimTopicsRegistry}/{@code trustedIssuersRegistry} permanently null, silently
     * breaking every trusted-issuer/claim-topic management call against those fields (finding
     * #6). Requires the deploying tx to already be mined and successful (callers only reach
     * this after {@code EvmContractService.send()} returns, which itself throws on revert).
     *
     * @throws IllegalStateException if the factory reports no token deployed for this salt
     */
    private Erc3643Suite resolveDeployedSuite(
            Web3j web3j, String factoryAddress, String salt, UUID deploymentId) {
        Function getSuiteAddresses = new Function(
                "getSuiteAddresses",
                List.of(new Utf8String(salt)),
                Arrays.asList(
                        new TypeReference<Address>() {}, new TypeReference<Address>() {},
                        new TypeReference<Address>() {}, new TypeReference<Address>() {},
                        new TypeReference<Address>() {}, new TypeReference<Address>() {})
        );
        List<Type> result = evmContractService.call(web3j, factoryAddress, getSuiteAddresses);

        String tokenAddress = (String) result.get(0).getValue();
        if (ZERO_ADDRESS.equalsIgnoreCase(tokenAddress)) {
            throw new IllegalStateException(
                    "EwpgTREXFactory.getSuiteAddresses(" + salt + ") returned no token — "
                            + "suite was not actually deployed under this salt");
        }

        Erc3643Suite suite = new Erc3643Suite();
        suite.setAssetDeploymentId(deploymentId);
        suite.setIsConfidential(false);
        suite.setTokenAddress(tokenAddress);
        suite.setIdentityRegistryAddress((String) result.get(1).getValue());
        suite.setIdentityRegistryStorage((String) result.get(2).getValue());
        suite.setTrustedIssuersRegistry((String) result.get(3).getValue());
        suite.setClaimTopicsRegistry((String) result.get(4).getValue());
        suite.setComplianceAddress((String) result.get(5).getValue());
        return suite;
    }

    /**
     * Seeds the DB-side required-claim-topics record (KYC + AML) for a freshly deployed suite,
     * mirroring the on-chain {@code ClaimTopicsRegistry} state set by {@link
     * #buildDeployEwpgSuiteFunction}. Without this, {@code IdentityRegistryService.isVerified}'s
     * suite-scoped topic lookup would find zero required topics for every new suite and
     * vacuously report every investor as verified.
     */
    private void seedDefaultClaimTopics(UUID suiteId) {
        Erc3643ClaimTopic kyc = new Erc3643ClaimTopic();
        kyc.setSuiteId(suiteId);
        kyc.setTopic(CLAIM_TOPIC_KYC);
        kyc.setLabel("KYC");
        claimTopicRepository.save(kyc);

        Erc3643ClaimTopic aml = new Erc3643ClaimTopic();
        aml.setSuiteId(suiteId);
        aml.setTopic(CLAIM_TOPIC_AML);
        aml.setLabel("AML");
        claimTopicRepository.save(aml);
    }

    // ── Signing helpers ───────────────────────────────────────────────────────
    // Claim signing itself goes through ClaimSigningService (see issueKycClaim), matching
    // OnchainID's real abi.encode(address,uint256,bytes) layout. encodeClaimId below encodes
    // only static types (address, uint256), so a packed concat is correct here with no
    // dynamic-type offset/length words needed.

    private static byte[] encodeClaimId(String issuer, long topic) {
        // keccak256(abi.encode(issuer_as_address, topic_as_uint256))
        byte[] packed = concat(
                leftPad20ToBytes32(hexToBytes(issuer.replace("0x", "").toLowerCase())),
                toBigEndian32(java.math.BigInteger.valueOf(topic))
        );
        return packed;
    }

    private static byte[] leftPad20ToBytes32(byte[] addr) {
        byte[] b = new byte[32];
        System.arraycopy(addr, 0, b, 12, Math.min(addr.length, 20));
        return b;
    }

    private static byte[] toBigEndian32(java.math.BigInteger value) {
        byte[] raw = value.toByteArray();
        byte[] padded = new byte[32];
        int srcPos = Math.max(0, raw.length - 32);
        System.arraycopy(raw, srcPos, padded, 32 - (raw.length - srcPos), raw.length - srcPos);
        return padded;
    }

    private static byte[] hexToBytes(String hex) {
        return Numeric.hexStringToByteArray("0x" + hex);
    }

    private static byte[] concat(byte[]... arrays) {
        int len = 0;
        for (byte[] a : arrays) len += a.length;
        byte[] result = new byte[len];
        int pos = 0;
        for (byte[] a : arrays) { System.arraycopy(a, 0, result, pos, a.length); pos += a.length; }
        return result;
    }
}
