/**
 * Live holder data from blockchain
 */
export interface LiveHolder {
  walletAddress: string;
  tokenBalance: number;
  lastUpdated?: Date;
  isWhitelisted?: boolean;
}

export interface MintAction {
  recipient: string;
  amount: number;
}

/**
 * Burn from a holder wallet (T3-01): needs the issuer's ASSET_TOKEN_ADMIN grant plus step-up and a
 * registry administrator's approval token scoped to `ISSUER_BURN_EWG26`.
 */
export interface BurnAction {
  amount: number;
  fromWallet: string;
  /** Authenticator (TOTP) code for built-in sign-in; omitted under Entra (claims challenge instead). */
  totpCode?: string;
  /** Second approver's step-up token, generated by a registry administrator for this action. */
  approvalToken: string;
}

export interface ForceTransferAction {
  fromWallet: string;
  toWallet: string;
  amount: number;
  legalBasis: string;
}

export interface ForceApproveAction {
  ownerWallet: string;
  spenderWallet: string;
  amount: number;
  legalBasis: string;
}
