/**
 * Live holder data from blockchain
 */
export interface LiveHolder {
  walletAddress: string;
  tokenBalance: number;
  lastUpdated?: Date;
  isWhitelisted?: boolean;
}

export interface MintAction {
  recipient: string;
  /** Decimal string of base units (no precision loss above 2^53). */
  amount: string;
  /** Authenticator (TOTP) code for built-in sign-in; omitted under Entra (claims challenge instead). */
  totpCode?: string;
  /** Second approver's step-up token (registry administrator / compliance officer) scoped to `ISSUER_MINT`. */
  approvalToken: string;
}

/**
 * Burn from a holder wallet (T3-01): needs the issuer's ASSET_TOKEN_ADMIN grant plus step-up and a
 * registry administrator's approval token scoped to `ISSUER_BURN_EWG26`.
 */
export interface BurnAction {
  /** Decimal string of base units (no precision loss above 2^53). */
  amount: string;
  fromWallet: string;
  /** Authenticator (TOTP) code for built-in sign-in; omitted under Entra (claims challenge instead). */
  totpCode?: string;
  /** Second approver's step-up token, generated by a registry administrator for this action. */
  approvalToken: string;
}

export interface ForceTransferAction {
  fromWallet: string;
  toWallet: string;
  /** Decimal string of base units (no precision loss above 2^53). */
  amount: string;
  legalBasis: string;
  /** Authenticator (TOTP) code for built-in sign-in; omitted under Entra (claims challenge instead). */
  totpCode?: string;
  /** Second approver's step-up token scoped to `ISSUER_FORCED_TRANSFER_EWG24`. */
  approvalToken: string;
}

export interface ForceApproveAction {
  ownerWallet: string;
  spenderWallet: string;
  /** Decimal string of base units (no precision loss above 2^53). */
  amount: string;
  legalBasis: string;  /** Authenticator (TOTP) code for built-in sign-in; omitted under Entra (claims challenge instead). */
  totpCode?: string;
  /** Second approver's step-up token scoped to `ISSUER_FORCED_APPROVE_OVERRIDE`. */
  approvalToken: string;
}
